OrdererOrgs:
  - Name: Orderer
    Domain: trappiste.fr
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1
      - Hostname: orderer2

PeerOrgs:
  - Name: Magasin
    Domain: magasin.trappiste.fr
    EnableNodeOUs: true
    Template:
      Count: 2
    Users: 
      Count: 0
      
  - Name: Chimay
    Domain: chimay.fournisseur.be
    EnableNodeOUs: true
    Template:
      Count: 2
    Users: 
      Count: 0
